name: Eslint check
on:
    pull_request:
        branches:
            - master

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: yarn
            - run: yarn lint
